### ISSUE TITLE
Dirty flag is incorrect for linked worktrees

### ISSUE THREAD

**Issue by koraktor** [koraktor/mavanagaiata#102]
The `commit`, `info-class` and `tag` goals flag linked worktrees as unclean in some situations.

See #100 

/cc @seanf Maybe you can provide more detail here as I’m unable to reproduce this at the moment.

**Comment by seanf** [comment]
@koraktor I've been doing all my testing with the `info-class` goal (and `cat target/**/GitInfo.java`), not the `commit` and `tag` goals, since I don't know of an easy way to see the properties they generate. So I don't know if they have the problem or not.

**Comment by koraktor** [comment]
Ok, `info-class` is affected, too. I forgot this one.
The other mojos now have debug output when run with `-X`.

Is your `pom.xml` in the root directory of your repository? I just found out that this might be another case where the dirty flag is incorrectly set.

**Comment by seanf** [comment]
@koraktor That's it! - it's in a subdirectory.

**Comment by koraktor** [comment]
Perfect, version 0.9.4 is on it’s way to Maven Central.

Fixed by 4c69043e78f45f2af18214788518c6ca131cbb87.

**Comment by seanf** [comment]
Looks good, thanks @koraktor !
