### ISSUE TITLE
Dirty flag doesn't play nice with maven-release-plugin

### ISSUE THREAD

**Issue by ctubbsii** [koraktor/mavanagaiata#34]
Builds with maven-release-plugin's release:perform goal always seem to append "-dirty". I don't know whether this is the result of the plugin using the wrong directory to compare when the git tag is checkout for a release build, or whether it is because the release plugin generates additional files as part of the build process that mavanagaiata doesn't ignore.

A workaround could be to add "-Dmavanagaiata.dirtyFlag=false" to the release profile, but it'd be better if mavanagaiata played nicely with the release plugin.

**Comment by koraktor** [comment]
@ctubbsii Did you test using the new branch? Would love to release a new version if this fixes your problems.

**Comment by ctubbsii** [comment]
Sorry, not yet. I haven't been able to find time. I should just be able to `mvn install` this to my localRepo, right? I can probably test tomorrow.

**Comment by koraktor** [comment]
Sure, `mvn install` should do the trick. You might want to modify the version in `pom.xml` so it doesn't overwrite the released 0.7.0.

**Comment by ctubbsii** [comment]
Tested, and it looks fixed! Thanks!

**Comment by koraktor** [comment]
Just (finally!) released version 0.7.1 with this fix. Should be available shortly.
