### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by spyhunter99** [koraktor/mavanagaiata#36]
My goal is to get the current git branch name and set it as a maven property. Can that be done with this plugin?

I essentially want to generate a filtered class that provides the builder's username, branch and date to make it easier to track test scenarios

**Comment by koraktor** [comment]
The example from the [`README`](https://github.com/koraktor/mavanagaiata/blob/master/README.md) should be sufficient for your use case. You can then use `mavanagaiata.branch` to get the branch.

Please have a look at the [documentation of the individual goals](http://koraktor.de/mavanagaiata/plugin-info.html) for more information.
