### ISSUE TITLE
No failure when building in non git repository

### ISSUE THREAD

**Issue by kawordix** [koraktor/mavanagaiata#39]
We would like to use your plugin in our continuous integration server while preserving the possibility to build a project locally.
Currently, the plugin fails the build when no git repository is present. This happens when the developer starts the work on a new project.
It would be great, if the plugin does not fail when there is no git repository present. All given information could be set to "unknown". Furthermore, this whole thing could be made optional.

**Comment by koraktor** [comment]
There's already a property for that: `mavanagaiata.skipNoGit`.

See #22.

**Comment by kawordix** [comment]
Thanks for your quick respond. 
Is this property mentioned in the [documentation](http://koraktor.de/mavanagaiata/plugin-info.html)? Because I think that is the reason I initially not found it.

**Comment by koraktor** [comment]
Yes, it's mentioned in the documentation. It's listed for every goal as it's a global setting.
