### ISSUE TITLE
Documentation for mavanagaiata:tag not up-to-date

### ISSUE THREAD

**Issue by StaticNoiseLog** [koraktor/mavanagaiata#40]
I think the documentation for mavanagaiata:tag does not list the correct properties:
http://koraktor.de/mavanagaiata/tag-mojo.html

The mentioned "mavanagaiata.tag" remains empty. The two properties that DO work for me with version 0.7.2 and the goal "tag" are:
${mavanagaiata.tag.name}
${mavanagaiata.tag.describe}

P.S: I found mavanagaiata very useful, thanks for providing it!

**Comment by koraktor** [comment]
Thanks for the heads-up.
