### ISSUE TITLE
HEAD could not be resolved on unborn branch

### ISSUE THREAD

**Issue by ctubbsii** [koraktor/mavanagaiata#42]
Executing within a git workspace without an initial commit results in the following error:

```
[ERROR] Failed to execute goal com.github.koraktor:mavanagaiata:0.7.1:commit (git-commit) on project testproject: Unable to read Git commit information: HEAD could not be resolved. You're probably on an unborn branch. -> [Help 1]
```

This failure occurs even with:

```
<skipNoGit>true</skipNoGit>
```

The expected behavior (my expectation, anyway) is that `skipNoGit` should prevent failure whenever you run in any directory without any git commits.

**Comment by koraktor** [comment]
Thanks for reporting.
This looks like a rare edge case, but it should be handled in a more appropriate way.

`skipNoGit` really means “skip plugin execution when we’re not in a Git repository”, which isn’t true for unborn branches. I don’t know if this should really be handled by this flag, though. Instead it might be more useful to warn the user and return some dummy information.

**Comment by ctubbsii** [comment]
Rather than an arbitrary dummy information, it might be worth using the git SHA1 for the empty tree object `git hash-object -t tree /dev/null`, which is always `4b825dc642cb6eb9a060e54bf8d69288fbee4904`. Further, in this situation, it'd always be "dirty", since its entire existence is in an uncommitted state. So, it would always be `4b825dc642cb6eb9a060e54bf8d69288fbee4904-dirty`, unless the option to suppress the dirty flag is turned on.

**Comment by koraktor** [comment]
Already thought about that when I wrote ”dummy information“. Guess that should work in all mojos.

**Comment by koraktor** [comment]
@ctubbsii I finally (!) found some time to have a look at this. There’s one problem with the `null` object, it’s not a commit. Most of the code expects a full commit object, though. I‘ll have another look on how to handle this.

**Comment by koraktor** [comment]
I decided to *not* handle this, i.e. we’ll just skip the mojo execution if an unborn branch is detected. I don’t think the additional work to get dummy results is worth it.

**Comment by ctubbsii** [comment]
Makes sense.
