### ISSUE TITLE
Missing dependency on slf4j implementation

### ISSUE THREAD

**Issue by ctubbsii** [koraktor/mavanagaiata#43]
Something changed between version 0.7.1 and 0.7.2. Version 0.7.2 now produces the following:

```
[INFO] --- mavanagaiata:0.7.2:commit (git-commit) @ build-resources ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

`slf4j-api` is a new dependency of `org.eclipse.jgit`, but it does not provide an implementation.

**Comment by ctubbsii** [comment]
I've tried creating a patch, but I can't test it, because the code in the `master` branch doesn't appear to produce a `commit` goal in the maven plugin. This might be due to the update to `maven-plugin-plugin` version `3.4`, which doesn't appear to properly parse the deprecated `@Component` annotations. I'm not sure.

**Comment by ctubbsii** [comment]
A workaround is to do this when you use `mavanagaiata` in your pom:

```
        <plugin>
          <groupId>com.github.koraktor</groupId>
          <artifactId>mavanagaiata</artifactId>
          <version>0.7.2</version>
          <dependencies>
            <dependency>
              <groupId>org.slf4j</groupId>
              <artifactId>slf4j-simple</artifactId>
              <version>1.7.2</version>
            </dependency>
          </dependencies>
        </plugin>
```

**Comment by koraktor** [comment]
That’s a non-fatal warning. So I guess there’s no need to fix it. Maybe there's a way to silence it?

I'm not entirely sure about the status of the current code in `master`. So yes, it might not produce the right goals.

**Comment by ctubbsii** [comment]
The fix is to add an slf4j implementation to mavanagaiata. Yes, the warning is non-fatal, but it can be fixed easily for 0.7.3. I recommend either slfj4-simple or slf4j-nop.

**Comment by koraktor** [comment]
Adding a SLF4J binding would result in problems when another binding is present in the calling project. So this doesn’t seem to be a good solution.

I’ll have a look at alternatives once I find some time.

**Comment by ctubbsii** [comment]
The interesting thing is that I've only noticed a problem with some versions of Maven. I wonder if Maven provides its own slf4j logger implementation in the framework in newer versions. Applying the workaround with different implementations, I haven't noticed any warnings resulting from multiple bindings.

Still, this plugin does have a runtime dependency on a logger implementation. I'll see if I can ping the Maven list and get somebody to comment here about what the best action to take is.

**Comment by ctubbsii** [comment]
I asked the question on the [Maven Dev list][1].

[1]: https://lists.apache.org/thread.html/3f163e3190944f5fdd5a4bcce6112bf89f60eb6e8a0606a46b82bdfe@%3Cdev.maven.apache.org%3E

**Comment by mgainty** [comment]
please explain this comment:

I've tried creating a patch, but I can't test it, because the code in the master branch doesn't appear to produce a commit goal in the maven plugin. This might be due to the update to maven-plugin-plugin version 3.4, which doesn't appear to properly parse the deprecated @Component annotations.
?

**Comment by ctubbsii** [comment]
@mgainty What part isn't clear? I tried to create a patch against the master branch to add the slf4j-simple dependency, but I couldn't get a successful build of the master branch. I received an error that the commit goal didn't exist.

The master branch has been updated to the latest maven-plugin-plugin dependency since the 0.7.2 release of this plugin. Earlier versions produced a warning that the `@Component` annotation was deprecated. I'm speculating that support for this feature was dropped. It's possible there's another reason I couldn't successfully build the master branch.

**Comment by mgainty** [comment]
as suggested at http://www.slf4j.org/codes.html#StaticLoggerBinder

 add this dependency:

	<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-nop</artifactId>
			<version>1.7.2</version>
		</dependency>

**Comment by koraktor** [comment]
Thanks for your input @mgainty.

According to [Maven’s class loading guide](http://maven.apache.org/guides/mini/guide-maven-classloading.html) each plugin uses its own class loader, so it should be safe to add `slf4j-nop` as a dependency.
