### ISSUE TITLE
Support for worktrees

### ISSUE THREAD

**Issue by koraktor** [koraktor/mavanagaiata#98]
JGit apparently does not support worktrees as of now: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475

But it should be possible to read the worktree file manually and redirect to the real repository path.

**Comment by seanf** [comment]
@koraktor I noticed that mavanagaiata 0.9.1 is reporting DIRTY = true when run in a fresh worktree (it's the original work dir that is dirty).
