### ISSUE TITLE
HTML for dependabot entry is broken in the Contributors page

### ISSUE THREAD

**Issue by seanf** [koraktor/mavanagaiata#99]
See https://koraktor.de/mavanagaiata/CONTRIBUTORS.html

    <li>dependabot<a href="46" rel="noreferrer">bot</a></li>

I think that's supposed to be something like this:

    <li>dependabot(46)</li>

It says "Generated by Mavanagaiata 0.9.1 at 02/05/2019 11:55 nachm. +0100"

**Comment by koraktor** [comment]
Thanks for the hint.

It‘s a Markdown problem. Dependabot‘s name is `dependabot[bot]`. This creates a link together with the number of commits `(46)`. This should be escaped.

I added HTML escaping for changelogs (97dafad02767a4083679a9d160183396def569ed), but Markdown should be escaped as well. And both should be applied to contributors as well.

**Comment by koraktor** [comment]
I pushed a quick manual fix to the site.
